<?php


/**
 * Implements hook_requirements().
 *
 * - Checks the mcrypt extension is installed on server.
 * 
 */
function commerce_cms_requirements($phase) {
  $requirements = array();

  if ($phase == 'install') {
    if (!extension_loaded('mcrypt')) {
      $requirements['mcrypt'] = [
        'description' => t('Commerce cms requires mcrypt extension. Make sure the extension is installed on server.'),
        'severity' => REQUIREMENT_ERROR,
      ];
    }
  }

  return $requirements;
}
